### PR TITLE
UID-147: Use type=password for auto login password field

### PR DESCRIPTION
**Pull request by julianladisch**
Refs [UID-147](https://issues.folio.org/browse/UID-147).

### CODE REVIEW

**Review by zburke — COMMENTED** [review]
I'm of two minds about this. 

1. Obviously passwords should be cloaked. No question. Let's merge this ASAP!
2. This developer-facing tool, designed to make development easier, is not intended for anything except ... you guessed it, development. Trying to "secure" this value by cloaking the display is beside the point. If anything, keeping this field cleartext could serve as a warning that things are (badly) misconfigured in production if there's a value here. Let's leave this alone!

I lean toward 2. 

@JohnC-80, @mkuklis, @MikeTaylor, @skomorokh, penny for your thoughts?

**Comment by skomorokh** [comment]
I kinda agree with both of your points but don't think they're incompatible: It shouldn't be enabled in production so this doesn't really matter but if it _is_ somehow enabled at least this way it won't be showing the password so it's not really bad to merge this per se since it'd be way more subtle than an actual warning which there probably should be...

**Review by MikeTaylor — COMMENTED** [review]
I'm sorry to say that I think both @zburke's points are of equal value, and I have no preference to contribute to this discussion.

**Comment by mkuklis** [comment]
Since we have this PR already opened let's merge it in :)

**Review by mkuklis — APPROVED** [review]

**Pull request merged**
