### PR TITLE
[STCOM-1265] Use shared timezones from stripes-components

### PR DESCRIPTION
**Pull request by ncovercash**
# [Jira STCOM-1265](https://folio-org.atlassian.net/browse/STCOM-1265)

The list of timezones was moves to stripes-components in https://github.com/folio-org/stripes-components/pull/2225; we should use the shared list to prevent duplication.

### CODE REVIEW

**Review by danetsao — APPROVED** [review]

**Comment by zburke** [comment]
@ncovercash , thanks for coordinating this effort across so many repos! Please note that to correctly track this work in Jira, it needs a UID ticket separate from the STCOM ticket, even though they're obviously related. When PRs in one repository link to a Jira ticket attached to another repository, we lose the ability to correctly set the "fix version" field. This reduces its visibility in Jira, and can be misleading about when an issue is fully resolved. A good option is to use a STRIPES or UXPROD issue as an umbrella or parent ticket that per-project tickets all link to. Yeah, more paperwork, sorry.

**Comment by ncovercash** [comment]
@zburke gotcha, I'll do that next time. Anything I should do to fix it this time?

**Comment by zburke** [comment]
@ncovercash nah; this is UID so no PO is watching Jira anyway. This is just me whining, "Next time, make sure you correctly file your TPS Report!" 😆  If PRs in other repos are also tied to STCOM-1265, you could clone it for each additional repo. This is an NFR ticket though. I personally wouldn't worry about it.

**Review by zburke — COMMENTED** [review]
@ncovercash, Thanks for cleaning up the redundant data structures here. I really appreciate it!

Please note: all PRs that change code MUST update CHANGELOG. If you're just adding tests or updating `yarn.lock` or something like that with no code changes, don't worry about it, but every other change deserves a mention. 

Breaking changes, especially, should be called out in CHANGELOG and this is, in fact, a breaking change since it requires work from stripes-components that won't be available until stripes v9.1.0. (Bumping a peer-dep, even if you only bump its minor or patch, is a breaking change.) Yes, I know the dep was already bumped in package.json, but the point is that this a change that relies on that bump in the peer-dep, and therefore deserves to be called out.

**Pull request merged**
